### ISSUE TITLE
Adding conjugated state preparation <0|, <1| ?

### ISSUE THREAD

**Issue by JarekDuda** [sw1sh/QuantumFramework#2]
Hello, 
I am working on two-way quantum computers (2WQC, https://arxiv.org/pdf/2308.13522) - extension adding conjugated state preparation: <0|, <1|.

For physical realization it needs to prepare a situation, such that looking from T/CPT symmetry perspective, we get the process used for state preparation - what seems realizable e.g. for silicon quantum dots below (e.g. https://www.nature.com/articles/s41467-020-20280-3 ), just using reversed impulse after.

As I believe it is a matter of time they will reach mainstream, I wanted to ask if <0|, <1| could be added to QuantumFramework?
Or maybe you could suggest how to technically do it and I will try myself - as in the diagram below, for current state it needs to multiply the qubits on the chosen positions, and then normalize the state.

![silicon](https://github.com/sw1sh/QuantumFramework/assets/6699208/12a1a01e-dd40-48ff-889e-f1e9e12cf7e9)

**Comment by sw1sh** [comment]
I don't currently understand what 2WQC is about yet. But we do have a simple state preparation algorithm implemented if you just provide a state to the QuantumCircuitOperator. And all other variations like daggers (bra) and operators are simply constructed by wiring inputs and outputs of the underlying prepared state with bent wires (Caps), which correspond to measurement with postselection:
<img width="644" alt="image" src="https://github.com/sw1sh/QuantumFramework/assets/1057888/d03c961d-1a60-4743-9772-fa624c5007e9">

**Comment by JarekDuda** [comment]
Thank you, I mean conjugated state preparation - like the above gray triangle <0|, but in the opposite direction |0>.
As in example in my diagram, for chosen qubit it needs to zero amplitudes for <0|1>=<1|0>=0, leave <0|0>=<1|1>=1, then normalize amplitudes.
It cannot be realized with other operations, it is close to postselection -  measure are discard unwanted cases.

For physical realization, we need to prepare a setting such that looking at it from CPT symmetry perspective ( https://en.wikipedia.org/wiki/CPT_symmetry ), we get process used for state preparation - like opposite impulse for the above silicon quantum dots.

I will probably prepare a notebook with examples in a few weeks to add to https://community.wolfram.com/web/dudaj - by trying to extract state and manually modify it.

**Comment by sw1sh** [comment]
> I mean conjugated state preparation - like the above gray triangle <0|, but in the opposite direction |0>.

Would you like to show them in the opposite direction, just diagrammatically?

`QuantumState["1"]["Dagger"]` is the conjugate state |1> of <1|.

This would make a diagram of it:
`QuantumCircuitOperator[{SuperDagger["1"]}]`

<img width="341" alt="image" src="https://github.com/sw1sh/QuantumFramework/assets/1057888/034b26c4-d2b3-4d4b-a8cc-80e83a9c9b8e">

I was simply showing that these two are equivalent:

<img width="377" alt="image" src="https://github.com/sw1sh/QuantumFramework/assets/1057888/6076ad5c-a8f0-4c5a-ac9b-e673e81338f1">

Underlying state preparation works only on Kets, for conjugation bent wires are added.

**Comment by JarekDuda** [comment]
Thanks indeed it works:

![Zrzut ekranu 2024-04-09 173026](https://github.com/sw1sh/QuantumFramework/assets/6699208/cdc58661-a1ef-4c88-97be-35ddf8ad77bc)

However, you can such state is no longer normalized ... but "ProbabilityPlot" handles (gets 1/2-1/2)  - seems it includes normalization (?)

Checked also more complicated and it works:

![Zrzut ekranu 2024-04-09 174647](https://github.com/sw1sh/QuantumFramework/assets/6699208/9524421a-0327-4792-8f68-5014e1e1f7c8)

So looks everything is fine, I will prepare a presentation and generally work on improving algorithms using this operation.
Great thanks!
